### ISSUE TITLE
Styling issues on the recipe page

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/site#19]
Currently the staging site has some issues with the styling. It needs to match the design.

You can compare the current [site](https://staging.sveltesociety.dev/recipes/build-setup) and the [design](https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=35%3A2)

I think it has to do with the styling sheet we're using, which is styling elements rather than using classes. Not sure what the right approach is there. At the moment we are skipping the sub-categories.

**Comment by stephane-vanraes** [comment]
How much of this has been resolved already ?

**Comment by kevmodrome** [comment]
There are some things to touch-up on the sidebar, like the hover and active states, Then also some elements are screwed up a bit if you look at the recipes, [like here](https://staging.sveltesociety.dev/recipes/stores) if you look at the pink box, not sure what to do with that.

We also need to implement the warning/take-note/extra information boxes (the ones that have a color and a left border (does that make sense?). I'm not sure what the best approach there is, just a component or modify a standard HTML element? I think having three components like `Warning.svelte`, `ReadMore.svelte` etc. with a slot is the way to go personally but i'm open to other ideas

**Comment by kevmodrome** [comment]
This is now fixed, thanks to @stephane-vanraes in #32
