### ISSUE TITLE
Recipe pages don't work on reload

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/site#20]
When going to the recipe page you can go to a recipe but if you do a hard-refresh or navigate straight to this page you will get an error. 

This indicates to me that these pages are not being exported correctly. Needs investigation.

**Comment by stephane-vanraes** [comment]
Some initial testing shows that:

1) The files are in the exported folder
![image](https://user-images.githubusercontent.com/13446670/86570230-e0ae0f00-bf6f-11ea-943f-0e7f60bb23fb.png)
2) Using `serve` locally on the dist folder works perfectly fine.

Note that currently on staging, going to
_https://staging.sveltesociety.dev/recipes/svelte-language-fundamentals/looping_ results in an error message stating "could not find recipes/svelte-language-fundamentals/looping/index.html in your content namespace"
and going to _https://staging.sveltesociety.dev/recipes/svelte-language-fundamentals/looping.html_ (a file that according to the export locally **has** to be there) gives a 404

This indicates that the exporting fails during the deploy itself and we would need some logging from the deployment

**Comment by kevmodrome** [comment]
Ah, interesting. This has to do with the Cloudflare Worker script then - I think it does some pattern matching to check the route and adds `/index.html`. The source for that is in the `workers-site` folder if you want to investigate further.

**Comment by stephane-vanraes** [comment]
I believe I found the offending code, in the `workes-site/index.js` we use the function `getAssetFromKV`, one of the parameters this can take is a `mapRequestToAsset` the default for this one is is found [here](https://github.com/cloudflare/kv-asset-handler/blob/deda2296c920405bd377c3d17394ac611a49e548/src/index.ts#L14) as you can see the default behaviour is to indeed add `index.html` to the path.

This means we have to override this option for our specific use case

**Comment by kevmodrome** [comment]
Got it! Maybe we should open an issue on their repo as well?

**Comment by kevmodrome** [comment]
This is now fixed!
