### ISSUE TITLE
mdsvex does not recognize code blocks marked with 'svelte'

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/site#23]
code blocks marked with **```svelte** are not processed correctly in mdsvex, instead they are just outputted as a single string, this will prevent us from getting fancy highlighting in the same way we could get here in github, this is a limitation of the processor mdsvex is using (prismjs)

a possible solution to this is to mark them as `html` instead
a more forward looking solution would be to keep them marked as `html` but somehow preprocess that to html instead ? (maybe this should be done by mdsvex itself)

**Comment by stephane-vanraes** [comment]
a third solution would be to write our own highlighter

**Comment by kevmodrome** [comment]
I think for now, just using `html` is probably the easiest. In the long run I can see value in doing that, maybe that's something that should actually be included in MDSveX, or as a plugin of some sort. Does @pngwgn (can I tag people like this? Hmm) maybe know what would be a good way forward here?

**Comment by stephane-vanraes** [comment]
@pngwn

**Comment by pngwn** [comment]
I don’t understand the problem. Can you please provide examples? I have svelte syntax highlighting on the mdsvex docs for example.

**Comment by stephane-vanraes** [comment]
The problem is that prismjs does not support svelte, but it seems you made a package for exactly this: [prism-svelte](https://github.com/pngwn/prism-svelte) which you probably use in the mdsvex docs

Will create a PR adding this here as well

Apologies for the disturbance

**Comment by kevmodrome** [comment]
That's great!

**Comment by pngwn** [comment]
I half remember including this in mdsvex by default but I may have imagined it. I’ll see if there is a simple way to do that.

**Comment by pngwn** [comment]
I imagined it. I’ll take a look at this.

**Comment by stephane-vanraes** [comment]
Managed to fix it by adding:

```js
import Prism from 'prismjs';
import 'prism-svelte';
```

to the rollup.config.js

**Comment by kevmodrome** [comment]
Neat!
