### ISSUE TITLE
Recipe code blocks do not show a monospaced font

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/site#44]
See screenshot.

<img width="813" alt="Screenshot 2020-07-22 at 21 42 59" src="https://user-images.githubusercontent.com/12690/88221233-7500bd00-cc64-11ea-97ec-056624c6d892.png">

**Comment by stephane-vanraes** [comment]
[prism.css line 29](https://github.com/svelte-society/site/blob/staging/static/prism.css#L29) has 
```css
font: 300 var(--code-fs)/1.7 var(--font-mono);
```

but there is no definition for `--code-fs` nor `--font-mono`

I would propose to simply change the font family to the generic `monospace` instead
